# general settings
name: unet_rcnn_192
model_type: UNetRCNNModel
num_gpu: auto
manual_seed: 0

# dataset and data loader settings
datasets:
  train:
    name: train
    type: Artery18TrainDataset
    dataroot: experiments/dataset/18artery/train
    # transforms
    a_min: -1200.0
    a_max: 400.0
    b_min: 0.0
    b_max: 1.0
    space_x: 1.5
    space_y: 1.5
    space_z: 2.0
    roi_x: 192
    roi_y: 192
    roi_z: 96
    RandFlipd_prob: 0.2
    num_samples: 1
    # RandRotate
    rotate_prob: 0.3
    rotate_range: 0.785
    # other
    center_crop: false
    enlarge_ratio: 1
    dataset_type: cache
    cache_rate: 1.0  # if use cache dataset
    # data loader
    use_shuffle: true
    workers: 16
    batch_size_per_gpu: 4
    pin_memory: true
    prefetch_mode: cuda

  val:
    name: validation
    type: Artery18ValidationDataset
    dataroot: experiments/dataset/18artery/val
    # transforms
    a_min: -1200.0
    a_max: 400.0
    b_min: 0.0
    b_max: 1.0
    space_x: 1.5
    space_y: 1.5
    space_z: 2.0
    # other
    valid_num: ~
    dataset_type: cache
    cache_rate: 1.0  # if use cache dataset
    # data loader
    workers: 4
    pin_memory: true
    
  val_train:
    name: validation(train)
    type: Artery18ValidationDataset
    dataroot: experiments/dataset/18artery/train
    # transforms
    a_min: -1200.0
    a_max: 400.0
    b_min: 0.0
    b_max: 1.0
    space_x: 1.5
    space_y: 1.5
    space_z: 2.0
    # other
    valid_num: 10
    dataset_type: cache
    cache_rate: 1.0  # if use cache dataset
    # data loader
    workers: 4
    pin_memory: true


# network structures
network:
  type: UNetRCNN
  spatial_dims: 3
  in_channels: 1
  out_channels: 20
  channels: [32, 64, 128, 256, 512]
  strides: [2, 2, 2, 2]
  num_res_units: 2
  act: LEAKYRELU
  norm: INSTANCE
  step_num: 2

# path
path:
  pretrain_network: ~
  param_key: params
  strict_load: ~
  # resume
  resume_state: ~

# training settings
train:
  optim:
    type: Adam
    lr: !!float 1e-2
    weight_decay: !!float 1e-3
    # weight_decay: 0

  scheduler:
    type: MultiStepLR 
    milestones: [2500, 5000, 10000, 20000, 40000, 60000]
    gamma: 0.1

    # type: CosineAnnealingRestartLR 
    # periods: [20000, 40000]
    # restart_weights: [1.0, 0.5]
    # eta_min: !!float 1e-8

  total_iter: 80000
  warmup_iter: 200
  bs: 1

  # losses
  # dice loss
  dice_opt:
    type: DiceLoss
    include_background: true
    to_onehot_y: true
    softmax: true
    loss_weight: !!float 1
    reduction: mean

# validation settings
val:
  val_freq: !!float 100
  save_img: false
  pbar: true

  model_inferer:
    sw_batch_size: 4
    infer_overlap: 0.4
    roi_size: [192, 192, 96]

  metrics:
    dice: # metric name
      type: DiceMetric
      to_onehot: 19
      include_background: true
      reduction: mean
      get_not_nans: false

# logging settings
logger:
  print_freq: 20
  save_checkpoint_freq: !!float 500
  use_tb_logger: true

# dist training settings
dist_params:
  backend: nccl
  port: 29500

find_unused_parameters: true
