# general settings
name: unet_baseline_pulmonary_seg
model_type: UNetModel
num_gpu: auto
manual_seed: 0

# dataset and data loader settings
datasets:
  train:
    name: train
    type: Artery18TrainDataset
    dataroot: experiments/dataset/18artery/train
    # transforms
    a_min: -1200.0
    a_max: 400.0
    b_min: 0.0
    b_max: 1.0
    space_x: 1.5
    space_y: 1.5
    space_z: 2.0
    roi_x: 160
    roi_y: 160
    roi_z: 96
    RandFlipd_prob: 0.2
    RandRotate90d_prob: 0.2
    RandScaleIntensityd_prob: 0.1
    RandShiftIntensityd_prob: 0.1
    # other
    enlarge_ratio: 1
    dataset_type: cache
    cache_rate: 1.0  # if use cache dataset
    # data loader
    use_shuffle: true
    workers: 8
    batch_size_per_gpu: 4
    pin_memory: true
    prefetch_mode: cuda

  val:
    name: validation
    type: Artery18ValidationDataset
    dataroot: experiments/dataset/18artery/val
    # transforms
    a_min: -1200.0
    a_max: 400.0
    b_min: 0.0
    b_max: 1.0
    space_x: 1.5
    space_y: 1.5
    space_z: 2.0
    # other
    valid_num: ~
    dataset_type: cache
    cache_rate: 1.0  # if use cache dataset
    # data loader
    workers: 4
    pin_memory: true
    
  val_train:
    name: validation(train)
    type: Artery18ValidationDataset
    dataroot: experiments/dataset/18artery/train
    # transforms
    a_min: -1200.0
    a_max: 400.0
    b_min: 0.0
    b_max: 1.0
    space_x: 1.5
    space_y: 1.5
    space_z: 2.0
    # other
    valid_num: 10
    dataset_type: cache
    cache_rate: 1.0  # if use cache dataset
    # data loader
    workers: 4
    pin_memory: true


# network structures
network:
  type: UNet
  spatial_dims: 3
  in_channels: 1
  out_channels: 19
  channels: [32, 64, 128, 256, 512]
  strides: [2, 2, 2, 2]
  num_res_units: 2
  act: LEAKYRELU
  norm: INSTANCE

# path
path:
  pretrain_network: ~
  param_key: params
  strict_load: ~
  # resume
  resume_state: ~

# training settings
train:
  optim:
    type: Adam
    lr: !!float 2e-4
    # weight_decay: !!float 1e-5
    weight_decay: 0

  scheduler:
    # type: MultiStepLR 
    # milestones: [4000, 8000, 12000, 16000]
    # gamma: 0.5

    type: CosineAnnealingRestartLR 
    periods: [10000, 20000, 20000, 30000]
    restart_weights: [1.0, 0.5, 0.5, 0.5]
    eta_min: !!float 1e-7

  total_iter: 80000
  warmup_iter: -1

  # losses
  # dice loss
  dice_opt:
    type: DiceCELoss
    include_background: false
    to_onehot_y: true
    softmax: true
    lambda_dice: 1.0
    lambda_ce: 0.1
    loss_weight: !!float 1
    reduction: mean

# validation settings
val:
  val_freq: !!float 100
  save_img: false
  pbar: true

  model_inferer:
    sw_batch_size: 4
    infer_overlap: 0.2

  metrics:
    dice: # metric name
      type: DiceMetric
      to_onehot: 19
      include_background: true
      reduction: mean
      get_not_nans: false

# logging settings
logger:
  print_freq: 20
  save_checkpoint_freq: !!float 500
  use_tb_logger: true

# dist training settings
dist_params:
  backend: nccl
  port: 29500

find_unused_parameters: true
